# Generated by Django 4.2.13 on 2024-05-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='schooladministrator',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
        ),
    ]
