# Generated by Django 4.2.13 on 2024-05-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_school_schooladministrator_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schooladministrator',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.school'),
            preserve_default=False,
        ),
    ]
