# Generated by Django 4.2.13 on 2024-05-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_school_alter_schooladministrator_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, to='core.student'),
        ),
    ]
